### ISSUE TITLE
No versioning available

### ISSUE THREAD

**Issue by petersamokhin** [appmetrica/appmetrica-sdk-ios#3] opened 2023-11-19 21:45 UTC
### 📚 AppMetrica SDK Version

That is the point — where are the SPM package versions?

### 🛠️ Xcode Version

whatever

### 📱 Device Information

whatever

### ⚙️ Installation Method

Swift Package Manager

### 📝 Description

No git tags are available in this repo. No versioning for Swift Package Manager is available.

### 🔍 Reproducing the issue

1. Open your repo
2. Feel disgusted and close it
3. Open again and look at the tags page, it's empty
4. Try to add a package using the repo URL in xcode
5. Only branch versioning available, no exact versions

**Comment by GLinnik21** [comment] 2023-11-19 22:07
Yes, this is correct. We do not have a release version for iOS at present. You may use .branchItem or .revisionItem for now in SPM or version 4 from the previous repository.
Closing as this is not a bug.

**Closed by GLinnik21** 2023-11-19 22:07 UTC
Labels: bug

**Comment by petersamokhin** [comment] 2023-11-19 22:14
Why not add versioning, not even talking about the changelogs? It is just a matter of `git tag` && `git push`
